tweet:
  message:
    - |
       【配信情報(自動)】
        ラジオ『変態百出』は毎週水曜日21:00〜配信中！

        <生配信>
        https://twitcasting.tv/c:hentai_hyakushutu/

        <収録配信>
        http://m.himalaya.fm/377553/album/367776/2/jp
    - |
       【配信情報(自動)】
        ラジオ『変態百出』は毎週水曜日21:00〜配信中！

        <生配信>
        https://twitcasting.tv/c:hentai_hyakushutu/

        <収録配信>
        http://hentai100shutu.seesaa.net/
    - |
       【配信情報(自動)】
        ラジオ『変態百出』は毎週水曜日21:00〜配信中！

        <生配信>
        https://twitcasting.tv/c:hentai_hyakushutu/

        <収録配信>
        https://www.youtube.com/channel/UCJ2YG0FdJEabGmwhs9nBNxw
    - |
        しゅん「なんてたってこのラジオは、地位と名誉とお金が大好きな二人がやってるからね」
        (第0回より)
    - |
        しゅん「こんばんワン！...何だこいつは」
        (第0回より)
    - |
        （方向音痴で好きな子とデートするのが不安という質問に対して）
        しゅん「一番は道を覚えろだし、もしそれがダメだったら迷ってる時間も彼女を楽しませてあげたらいいんじゃない？」
        じゅん「カッコイイ^^」
        しゅん「ウェーイ^^」
        (第0回より)
    - |
        じゅん「リスナーさんが「カッコイイ！」だって」
        しゅん「カッコイイだろ？見習ってください」
        (第0回より)
