tweet:
  message:
    - |
       【配信情報】
        ラジオ『変態百出』は毎週水曜日21:00〜配信中！

        <生配信>
        https://twitcasting.tv/c:hentai_hyakushutu/

        <収録配信>
        http://m.himalaya.fm/377553/album/367776/2/jp
    - |
       【配信情報】
        ラジオ『変態百出』は毎週水曜日21:00〜配信中！

        <生配信>
        https://twitcasting.tv/c:hentai_hyakushutu/

        <収録配信>
        http://hentai100shutu.seesaa.net/
    - |
       【配信情報】
        ラジオ『変態百出』は毎週水曜日21:00〜配信中！

        <生配信>
        https://twitcasting.tv/c:hentai_hyakushutu/
        
        <収録配信>
        https://www.youtube.com/channel/UCJ2YG0FdJEabGmwhs9nBNxw
