tweet:
  message:
    - |
       【配信情報(自動)】
        ラジオ『変態百出』は毎週水曜日21:00〜配信中！

        <生配信>
        https://twitcasting.tv/c:hentai_hyakushutu/

        <収録配信>
        http://m.himalaya.fm/377553/album/367776/2/jp
    - |
       【配信情報(自動)】
        ラジオ『変態百出』は毎週水曜日21:00〜配信中！

        <生配信>
        https://twitcasting.tv/c:hentai_hyakushutu/

        <収録配信>
        http://hentai100shutu.seesaa.net/
    - |
       【配信情報(自動)】
        ラジオ『変態百出』は毎週水曜日21:00〜配信中！

        <生配信>
        https://twitcasting.tv/c:hentai_hyakushutu/

        <収録配信>
        https://www.youtube.com/channel/UCJ2YG0FdJEabGmwhs9nBNxw
    - |
        しゅん「なんてたってこのラジオは、地位と名誉とお金が大好きな二人がやってるからね」
        (第0回より)
    - |
        しゅん「こんばんワン！...何だこいつは」
        (第0回より)
    - |
        （方向音痴で好きな子とデートするのが不安という質問に対して）
        しゅん「一番は道を覚えろだし、もしそれがダメだったら迷ってる時間も彼女を楽しませてあげたらいいんじゃない？」
        じゅん「カッコイイ^^」
        しゅん「ウェーイ^^」
        (第0回より)
    - |
        じゅん「リスナーさんが「カッコイイ！」だって」
        しゅん「カッコイイだろ？見習ってください」
        (第0回より)
    - |
        しゅん「変態百出ってどういう意味ですか？」
        じゅん「そういえば、0回の時に話さなかったね(笑)」
        (第1回より)
    - |
        じゅん「0回配信やりましたけれども、どうでした？聴いてみた？」
        しゅん「聴いた聴いた」
        じゅん「どうだった？」
        しゅん「えっ…、面白かったよ？」
        (第1回より)
    - |
        しゅん「会社についてはちょっとやめよ？暗くなっちゃう」
        (第1回より)
    - |
        じゅん「いやぁもう皆ね、フレッシュ。そこら辺のオヤジと比べて枯れてないもん」
        しゅん「お前がもう既におじさんだよ」
        (第1回より)
    - |
        しゅん「みなさんもね、なんか怖い話・恐怖体験送って欲しいな」
        しゅん「もし、可能なら心霊写真付きで」
        じゅん「やめてよ、俺の端末で開くんでしょ？」
        (第1回より)
    - |
        じゅん「添付ファイルがついてたら一発で消しますから」
        (第1回より)
    - |
        しゅん「あの幽霊ホテルの？」
        じゅん「そういう言い方もよくない、それはもう営業妨害だからダメだよ」
        (第1回より)
